
- name:  Set up Jenkins
  hosts: launched
  user : ec2-user
  sudo : yes
  gather_facts: true

  tasks:
    - fail: msg="Cannot continue, the OS is not RPM based"
      when: ansible_os_family != 'RedHat'

    # Naturally this isn't essential!
    - name: Ensure aliases present
      sudo: yes
      copy: src=files/aliases.sh
            dest=/etc/profile.d/aliases.sh
            owner=root group=root mode=0644

    - name: Ensure Jenkins Yum repo present
      sudo: yes
      get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
               dest=/etc/yum.repos.d/jenkins.repo mode=0644

    - name: Ensure Jenkins GPG key installed
      sudo: yes
      command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: Ensure Jenkins installed
      sudo: yes
      yum: name=jenkins state=present
      notify:
          - restart jenkins


  handlers:
      - name: restart jenkins
        sudo: yes
        service: name=jenkins state=restarted
