- hosts: launched
  user: ec2-user
  sudo: yes
  vars:
   mysql_root_password: pass123
  tasks:
    - name: Install MySQL
      yum:
        name: "{{ item }}"
      with_items:
        - MySQL-python
        - mysql-server
        - mysql
        - php
        - php-mysql

    - name: Start the MySQL service
      action: service name=mysqld state=started

    - name: Configure the root credentials
      action: command mysqladmin -u root password $mysql_root_password
    
    - name: copy .my.cnf file with root password credentials
      template: src=files/my.cnf dest=/root/.my.cnf owner=root mode=0600





